### ISSUE TITLE
Locking orientation of RTCView

### ISSUE THREAD

**Issue by sbaar** [oney/react-native-webrtc#220]
On an ios app that only supports portrait, when rotating the device the camera preview will disappear then reappear in landscape, even when the rest of the ui stays in portrait. Is there any way to prevent this behavior and keep it locked to portrait?

It looks like there would be a way to lock it if we had access to the underlying avcapture connection but  I can only find a reference to a AVCaptureSession in RTCAVFoundationVideoSource and that does not seem sufficient.

**Comment by daxfrost** [comment]
I want the same thing!

**Comment by sbaar** [comment]
I was able to stop the rotation by calling the following code after app launch in a native module. It tells the device to stop generating orientation notifications whenever one pops up, and that seems to stop whatever webrtc is listening for.

```
#import "RCTBridgeModule.h"
#import "ReactSettings.h"
@implementation ReactSettings

RCT_EXPORT_MODULE();
RCT_EXPORT_METHOD(endRotationNotifications){

      [[NSNotificationCenter defaultCenter] addObserver:self  selector:@selector(orientationChanged:)    name:UIDeviceOrientationDidChangeNotification  object:nil];
  
}
- (void)orientationChanged:(NSNotification *)notification{
  NSLog(@"orientation changed");
  [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
}


@end
```

**Comment by thehappycoder** [comment]
@sbaar Do you have an example with more context?

**Comment by daxfrost** [comment]
@thehappycoder I simply called the following line on startup.

[[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];

**Comment by thehappycoder** [comment]
When I call it on startup, nothing happens.

**Comment by thehappycoder** [comment]
@sbaar Please reopen the task as your workaround doesn't work. I'd prefer proper solution anyway.

**Comment by nbr625** [comment]
@thehappycoder Did you resolve this? Also from where are you importing ReactSettings to call, endRotationNotifications()? You seem to be the only one on the search engine who has mentioned it.

**Comment by thehappycoder** [comment]
I tried changing avcapture connection's orientation but that brought even more problems after I noticed that the recorded video got upside down :) (the subscriber could see it just fine though).

I ended up using [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications]; in a hacky way. I don't even understand yet how it works but it works! It locks the device orientation. In one place of the project I do this:
```
[[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
      
      [[NSOperationQueue mainQueue] addOperationWithBlock:^ {
        [[UIDevice currentDevice] setValue:[NSNumber numberWithInt:UIDeviceOrientationLandscapeLeft] forKey:@"orientation"];
        
        [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
      }];
```

In deviceOrientationDidChange (that is called by   [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(deviceOrientationDidChange:) name:UIDeviceOrientationDidChangeNotification object:nil];
):
```
[[UIDevice currentDevice] setValue:[NSNumber numberWithInt:UIDeviceOrientationLandscapeRight] forKey:@"orientation"];
      
      while ([[UIDevice currentDevice] isGeneratingDeviceOrientationNotifications]) {
        L_INFO(@"Calling endGeneratingDeviceOrientationNotifications")
        [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
      }
```

When I get time to figure it out, I'll leave a note here.

**Comment by JoostVermeulen11** [comment]
Is there a solution yet? I am facing this issue too and don't know how to keep the RTCView away from rotating.. (I locked the app in landscape mode, the only object that is still rotating is the RTCView)

**Comment by notedit** [comment]
same issuse

**Comment by szoszig** [comment]
If you build webrtc library on your own ([webrtc source](https://webrtc.org/native-code/ios/)), than you should modify a file in the source:

> ..webrtc/src/webrtc/sdk/objc/Framework/Classes/Video/RTCAVFoundationVideoCapturerInternal.mm

In this file, there is a method called captureOutput. There is a section in it, that handles rotation on iOS. If you comment it out, and set a default rotation you prefer, and build the framework, it should work as expected.

**Comment by cristiantx** [comment]
I've ended up doing what @szoszig suggested.

Modified the file
```
(...)WebRTC/src/sdk/objc/Framework/Classes/Video/RTCAVFoundationVideoCapturerInternal.mm
```

Commented out this block, around line 237
```
switch (_orientation) {
    case UIDeviceOrientationPortrait:
      rotation = webrtc::kVideoRotation_90;
      break;
    case UIDeviceOrientationPortraitUpsideDown:
      rotation = webrtc::kVideoRotation_270;
      break;
    case UIDeviceOrientationLandscapeLeft:
      rotation = usingFrontCamera ? webrtc::kVideoRotation_180 : webrtc::kVideoRotation_0;
      break;
    case UIDeviceOrientationLandscapeRight:
      rotation = usingFrontCamera ? webrtc::kVideoRotation_0 : webrtc::kVideoRotation_180;
      break;
    case UIDeviceOrientationFaceUp:
    case UIDeviceOrientationFaceDown:
    case UIDeviceOrientationUnknown:
      // Ignore.
      break;
  }
```

And forced Landscape placing just this:
```
  rotation = usingFrontCamera ? webrtc::kVideoRotation_180 : webrtc::kVideoRotation_0;
```

After that I build the framework using this commands, remember not to sign the bundle because you'll probably have entitlements conflict issues otherwise.

```
$ gn gen out/ios_64 --args='target_os="ios" target_cpu="arm64" is_debug=false ios_enable_code_signing=false' --ide=xcode
$ ninja -C out/ios framework_objc
```

**Comment by bighitbiker3** [comment]
@cristiantx When submitting to the app store with that approach did you ever get an error in your email like `Invalid Bundle - Ensure that app executables and bundled frameworks use consistent architectures`? I can't figure it out...

**Comment by cristiantx** [comment]
@bighitbiker3 Found that the command line I've posted is not enough to generate both architectures. I've ended up finding a PYTHON script in WebRTC folder that do what we want, but I had to change one line... of this file `/src/tools_webrtc/ios/build_ios_libs.py` 

Modify this line:
```
DEFAULT_ARCHS = ENABLED_ARCHS = ['arm64', 'arm', 'x64', 'x86']
```
to:
```
DEFAULT_ARCHS = ENABLED_ARCHS = ['arm64', 'arm']
```

Then just run `build_ios_libs.sh`. You can run it with `--help` to see the options but the reason I modified the script is because if you pass multiple archs by params it doesn't "combine" all the archs in one framework. But if you let it as default, it does. And that's what we want.

You are probably having that issue, you have just the output of one of those archs.

I've published it to the App Store after that.

**Comment by bighitbiker3** [comment]
You rock! Thank you

**Comment by pablogeek** [comment]
Hello guys, I'm still having this issue and `UIDevice.current.endGeneratingDeviceOrientationNotifications()` didn't solve my problem (I'm using swift) 

Does anyone has a proper solution?

Thanks

**Comment by FedericoHenze** [comment]
The solution of @sbaar works for me...  First, listen for the notification and inside the handler disable it.

**Comment by chengsam** [comment]
Solution of @sbaar not worked for me, and calling `UIDevice.current.endGeneratingDeviceOrientationNotifications()` directly not worked either. I can't believe there's no simple way to do it.

**Comment by vanhungoz** [comment]
anyone have a simple solution to handle it?

**Comment by passpier** [comment]
I've try solution of @sbaar but it made iOS crash. Call`[[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];` throw exception message "threading violation: expected the main thread". Thus I directly set orientation value of `UIDevice`, and  it worked for me.
```
#import "RCTBridgeModule.h"
#import "ReactSettings.h"
@implementation ReactSettings

RCT_EXPORT_MODULE();
RCT_EXPORT_METHOD(endRotationNotifications){
  [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(orientationChanged:) name:UIDeviceOrientationDidChangeNotification  object:nil];
}

- (void)orientationChanged:(NSNotification *)notification{
  NSNumber *value = [NSNumber numberWithInt:UIInterfaceOrientationLandscapeRight];
  [[UIDevice currentDevice] setValue:value forKey:@"orientation"];
}


@end
```

**Comment by vadympetryshyn** [comment]
Solutions in this issue is outdated, any ideas how to solve this problem?

**Comment by Mustachipleb** [comment]
Bumping, would quite like to know as well.

**Comment by slycoder** [comment]
I believe the proper solution should be to use the orientation tracking functionality added in v4 of the api.  Documentation here: https://www.twilio.com/docs/video/ios-v4-video-source-apis#tracking-orientation-changes 

Unfortunately I don't have time to implement this at the moment but if anyone else wants to give it a shot, let us know how it goes.

**Comment by saghul** [comment]
Not sure how that would translate here, since we don't use Twilio at all in this plugin.

**Comment by slycoder** [comment]
@saghul Oof, sorry, posted on the wrong repo.  I'll delete my message and try to get some sleep =0.

**Comment by 8BallBomBom** [comment]
Have you tried [this](https://github.com/wonday/react-native-orientation-locker) module?
Might resolve the issue.

As it stands this is marked as not planned/out of scope.
On the other hand we're open to contributions and as such a pr might get accepted.
