### ISSUE TITLE
Rear-facing camera access

### ISSUE THREAD

**Issue by nickfujita** [oney/react-native-webrtc#9]
Thanks for making this module! I am in the process of integrating it into my app, and was wondering if there is a way to toggle the camera between the front-facing and rear-facing camera?

**Comment by oney** [comment]
I will be working on it on this weekend!

**Comment by nickfujita** [comment]
Awesome! Thanks for the quick response! Looking forward to your update this weekend.

**Comment by oney** [comment]
0.2.3 support it!
```javascript
navigator.getUserMedia({
    "audio": true,
    "video": true,
    "videoType": "back" // optional, values is `back`, `front`
  }, function (stream) {
```

**Comment by nickfujita** [comment]
Cool, so now you can set it to back when you init with get user media, but is there a function I can call or property I can set to toggle the stream from front to back when an event occurs?

**Comment by oney** [comment]
Please try 0.2.4, toggling should work.

```javascript
var frontStream, backStream;

navigator.getUserMedia({
  "audio": true,
  "video": true,
  "videoType": "front"
}, function (stream) {
  frontStream = stream;
}, logError);

navigator.getUserMedia({
  "audio": true,
  "video": true,
  "videoType": "back"
}, function (stream) {
  backStream = stream;
}, logError);


var TheApp = React.createClass({
  _useFront() {
    this.setState({streamURL: frontStream.toURL()});
  },
  _useBack() {
    this.setState({streamURL: backStream.toURL()});
  },
  render: function() {
    return (
      <View style={styles.container}>
        <RTCView streamURL={this.state.streamURL}/>
      </View>
    );
  }
});
```

**Comment by nickfujita** [comment]
I will try this out today!

Just curious, But does creating 2 streams have an affect on performance? Having one stream up already seems to take a toll on the system. Is there not a way to toggle from front to back on a single existing stream?

**Comment by oney** [comment]
Something I forgot to tell. When you switch streams, peerConnection should removeStream and then addStream
```javascript
peerConnection.removeStream(oldStream);
peerConnection.addStream(newStream);
```
You can get the stream from navigator.getUserMedia when you need it. After you don't need the stream, you can call `stream.release()` to release it.

According [doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream), changing the track of the stream should be implemented too by using `addTrack` and `removeTrack`. If I have time, I will do it!

**Comment by nickfujita** [comment]
While testing out the latest version with my current project, it appears that there were some changes made between 0.2.2 and 0.2.5 that are causing my build to fail. It appears that the change in RTCVideoViewManager.m shown below, is the failing point.

-    WebRTCModule *module = self.bridge.modules[@"WebRTCModule"];
 +    WebRTCModule *module = [self.bridge moduleForName:@"WebRTCModule"];

What was the reason for this change, as it looks like they are doing the same thing, just in a slightly different way?

Thanks!

**Comment by oney** [comment]
Using `self.bridge.modules` to get module is deprecated from 0.17.0. But, `moduleForName` is not supported before 0.17.0. I think I am too early to upgrade it. I will use `self.bridge.modules` in 0.2.6.

**Comment by nickfujita** [comment]
Thanks for looking into that Howard! I'll look to retest in 0.2.6.

**Comment by nickfujita** [comment]
Tried updating the version to 0.2.6 in my existing app, and adding the property videoType to the getUserMedia call, but am getting the following error:

-12-30 14:46:40.576 RCTWebRTCDemo[8779:2575324] -[RTCVideoTrack copyWithZone:]: unrecognized selector sent to instance 0x12cfd2590
2015-12-30 14:46:40.577 [error][tid:main][RCTUIManager.m:884] Error setting property 'streamURL' of RTCVideoView with tag #7: Error setting property 'streamURL' of RTCVideoView with tag #7: Exception thrown while executing UI block: -[RTCVideoTrack copyWithZone:]: unrecognized selector sent to instance 0x12cfd2590

My app is closely based on the [example that was provided](https://github.com/oney/RCTWebRTCDemo), so I went back to test on a fresh copy. The example that you updated with 0.2.3 seems to work fine, but after I updated the version to 0.2.6, I am getting the same error that I was getting when running 0.2.6 on my existing project.

**Comment by nickfujita** [comment]
Just reverted back the version on my existing app to 0.2.3 since it was working with the example app, and sure enough, the back camera is working when I set the videoType to back! However, it looks like I am going to need your changes from 0.2.5 in order to remove the video stream when switching between the 2.

**Comment by oney** [comment]
Sorry. It is fixed in 0.2.7.
Now you can test switching video type in [RCTWebRTCDemo](https://github.com/oney/RCTWebRTCDemo)

**Comment by jcgertig** [comment]
in 0.3.0 when I define the `videoType` the `getUserMedia` call fails

**Comment by oney** [comment]
On iOS? Can you get some logs to me?

**Comment by jcgertig** [comment]
what kind of logs It just does not resolve.

```
navigator.getUserMedia({
        'audio': true,
        'video': true,
        'videoType': 'front', // optional, values are `back` & `front`
      }, (stream) => {
        console.log('Got it');
        resolve(stream);
      }, (err) => {
        console.log('Nope');
        reject(err);
      });
```

neither of these `console.log`s get called.

**Comment by jcgertig** [comment]
with the `videoType` removed it works

**Comment by jcgertig** [comment]
but defaults to the back cam

**Comment by jcgertig** [comment]
oh yes iOS

**Comment by oney** [comment]
Please find `node_modules/react-native-webrtc/RCTWebRTC/Classes/WebRTCModule+RTCMediaStream.m`
Change codes from line 49 to 69
```objective-c
    if (constraints[@"videoType"]) {
      NSLog(@"videoType: %@", constraints[@"videoType"]);
      NSNumber *positionObject = [self captureDevicePositionFrom:constraints[@"videoType"]];
      NSLog(@"positionObject: %@", positionObject);
      if (positionObject == nil) {
        videoDevice = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo];
      } else {
        AVCaptureDevicePosition position = [positionObject integerValue];
        NSLog(@"position: %li", (long)position);
        
        for (AVCaptureDevice *device in devices) {
          if (device.position == position) {
            videoDevice = device;
            break;
          }
        }
        
        if (!videoDevice) {
          videoDevice = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo];
        }
      }
    } else {
      videoDevice = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo];
    }
```
And run to get some logs on Xcode.

**Comment by jcgertig** [comment]
<img width="786" alt="screen shot 2016-02-28 at 3 35 52 pm" src="https://cloud.githubusercontent.com/assets/455355/13381715/04e7c93a-de31-11e5-980d-9658e125fb14.png">

**Comment by oney** [comment]
Interesting... It shouldn't crash on NSLog.
Same file, find line 36, add this above `NSNumber *objectID = @(self.mediaStreamId++);`
```
  NSLog(@"constraints: %@", constraints);
```

**Comment by jcgertig** [comment]
its working now with that NSLog but if i remove it it fails again :|

**Comment by jcgertig** [comment]
I still get another issue as well https://github.com/oney/react-native-webrtc/issues/20

**Comment by jcgertig** [comment]
I found the issue it was a small syntax thing where I had a default value in a var for the side but it was defaulting to a object because of it

**Comment by jcgertig** [comment]
thanks

**Comment by zxcpoiu** [comment]
implemented
